# Welcome to numpy toturial

print("Hello world")

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int32)

In [3]:
myarr

array([[ 3,  6, 32,  7]])

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr[0,1]

6

In [7]:
myarr[0,2]=36 

In [8]:
myarr

array([[ 3,  6, 36,  7]])

# Array creation: Conversion from other Python strcture

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({32,33,12})

array({32, 33, 12}, dtype=object)

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1,50,50)

In [27]:
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [30]:
emp = np.empty((4,6))  #gives empty array which have garbage values initially

In [31]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [35]:
ide = np.identity(5)  #gives identity matrix

In [36]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
ide.shape

(5, 5)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr = arr.reshape(3,33)  #reshape can happen only when matri can be divided into number given in colmn option

In [43]:
arr.shape

(3, 33)

In [45]:
arr.ravel()   #make it to 1-D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [47]:
ar = np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0)  #axis 0 is considered as row-wise axis

array([12,  8,  9])

In [50]:
ar.sum(axis=1)   #axis 1 is considered as column-wise axis

array([ 6, 15,  8])

In [51]:
ar.T  #transpose the matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim   #number of dimentions

2

In [54]:
ar.size    #number of elements

9

In [55]:
ar.nbytes    #bytes consumed by array

36

In [56]:
one = np.array([1,3,4,634,2])

In [57]:
one.argmax()   #index of max element

3

In [58]:
one.argmin()   #index of min element

0

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.argmin()

8

In [61]:
ar.argmax()

6

In [62]:
ar.argmax(axis=0)    #return index array of row axis 

array([2, 1, 1], dtype=int64)

In [64]:
ar.argmax(axis=1)    #return index array of column axis

array([2, 2, 0], dtype=int64)

In [65]:
ar.argsort()     #return index matrix in which singular array-wise indecates which index require to sort array

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.argsort(axis=0)    #return index matrix in which row-wise indecates which index require to sort array

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [68]:
ar.argsort(axis=1)    #return index matrix in which column-wise indecates which index require to sort array

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [69]:
myarr

array([[ 3,  6, 36,  7]])

In [70]:
defArray = [2, 4, 6, 1]

In [71]:
myarr + defArray

array([[ 5, 10, 42,  8]])

In [72]:
myarr2 = np.array([1, 2, 3, 4])

In [73]:
myarr + myarr2

array([[ 4,  8, 39, 11]])

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar2 = np.array([[3, 2, 1],[6, 5, 4], [0, 7, 1]])

In [76]:
ar2

array([[3, 2, 1],
       [6, 5, 4],
       [0, 7, 1]])

In [77]:
ar + ar2

array([[ 4,  4,  4],
       [10, 10, 10],
       [ 7,  8,  1]])

In [78]:
ar * ar2

array([[ 3,  4,  3],
       [24, 25, 24],
       [ 0,  7,  0]])

In [79]:
ar.sum()

29

In [80]:
ar.max()

7

In [81]:
ar.min()

0

In [82]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [85]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
np.where(ar>1)   #read output column-wise

(array([0, 0, 1, 1, 1, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0], dtype=int64))

In [88]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [97]:
np.arange(2,dtype=complex)

array([0.+0.j, 1.+0.j])